### ISSUE TITLE
백엔드 설계 - 어트랙션

### ISSUE THREAD

**Issue by chchcoco** [project-TravleJ/backend#3]
## todo list

- [x] 어트랙션 등록
- [x] 어트랙션 수정
- [x] 어트랙션 전체 조회
- [x] 어트랙션 상세 조회
- [x] 어트랙션 삭제

**Comment by leebumsung** [comment]
어트랙션 수정 기능 구현중

**Comment by leebumsung** [comment]
어트랙션 CRUD 구현완료
